### ISSUE TITLE
cqc_changes : Error in `dplyr::bind_rows()`: ! Argument 1 must be a data frame or a named atomic vector.

### ISSUE THREAD

**Issue by simondashnash** [evanodell/cqcr#2]
Hi

I ran this snippet  and got the error in the title. Hope the copy+paste traces below will help.

changes_location <- cqc_changes(organisation_type = c("location"),
                                start_date = "2000-01-01", end_date = Sys.Date(), verbose = TRUE,
                                clean_names = TRUE)

I am using cqcr 0.1.3.9000 from github, and R 4.2.3. On Win10.

> rlang::last_error()
<error/rlang_error>
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
---
Backtrace:
 1. cqcr::cqc_changes(...)
 2. cqcr:::cqc_get_data(...)
 3. cqcr:::cqc_multi_page_get_data(...)
 4. dplyr::bind_rows(cont[[type]])

> rlang::last_trace()
<error/rlang_error>
Error in `dplyr::bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
---
Backtrace:
    ▆
 1. └─cqcr::cqc_changes(...)
 2.   └─cqcr:::cqc_get_data(...)
 3.     └─cqcr:::cqc_multi_page_get_data(...)
 4.       └─dplyr::bind_rows(cont[[type]])
 5.         └─rlang::abort(glue("Argument {i} must be a data frame or a named atomic vector."))

**Comment by evanodell** [comment]
I've pushed an update that should fix it, could you try with the latest development version?

**Comment by simondashnash** [comment]
Thanks, that works now. R still tells me I am using version 0.1.3.9000 even though I removed and then ran devtools::install_github("evanodell/cqcr")
